global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerting/prometheus-rules.yaml

scrape_configs:
  - job_name: activity-service
    static_configs:
      - targets:
          - activity-service:8080
  - job_name: activity-dlq-manager
    static_configs:
      - targets:
          - activity-dlq-manager:9096
  - job_name: activity-consumer
    static_configs:
      - targets:
          - activity-consumer:9095
  - job_name: identity-service
    static_configs:
      - targets:
          - identity-service:8000
