openapi: 3.1.0
info:
  title: Activity Service API
  version: 0.1.0
  description: 'REST API for logging and retrieving fitness activities.

    '
  contact:
    name: Platform Engineering
    email: platform@example.com
servers:
- url: http://localhost:8080
tags:
- name: Activities
  description: Endpoints for creating and retrieving tenant-scoped activities.
security:
- bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Activity:
      type: object
      properties:
        activity_id:
          type: string
        tenant_id:
          type: string
        user_id:
          type: string
        activity_type:
          type: string
        started_at:
          type: string
          format: date-time
        duration_min:
          type: integer
        source:
          type: string
        version:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        failure_reason:
          type: string
          description: Most recent DLQ failure message associated with the activity, if any.
        next_retry_at:
          type: string
          format: date-time
          description: Timestamp when the DLQ manager will attempt another replay.
        quarantined_at:
          type: string
          format: date-time
          description: When the DLQ entry was quarantined after exhausting retries.
        replay_available:
          type: boolean
          description: Indicates whether the activity is queued for replay (quarantine absent).
      required:
      - activity_id
      - tenant_id
      - user_id
      - activity_type
      - started_at
      - duration_min
      - source
      - version
      - status
    ActivityMetricsSummary:
      type: object
      properties:
        total:
          type: integer
        pending:
          type: integer
        synced:
          type: integer
        failed:
          type: integer
        average_duration_minutes:
          type: number
          format: float
        average_processing_seconds:
          type: number
          format: float
        oldest_pending_age_seconds:
          type: number
          format: float
        success_rate:
          type: number
          format: float
        last_activity_at:
          type: string
          format: date-time
    ActivityMetricsResponse:
      type: object
      properties:
        summary:
          $ref: '#/components/schemas/ActivityMetricsSummary'
        timeline:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
        timeline_limit:
          type: integer
        window_seconds:
          type: integer
paths:
  /v1/activities:
    post:
      summary: Create activity
      description: Submit a new fitness activity for ingestion and asynchronous processing.
      security:
      - bearerAuth: []
      tags:
      - Activities
      operationId: createActivity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                activity_type:
                  type: string
                started_at:
                  type: string
                  format: date-time
                duration_min:
                  type: integer
                source:
                  type: string
              required:
              - user_id
              - activity_type
              - started_at
              - duration_min
              - source
      responses:
        '202':
          description: Accepted - new activity pending processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  activity_id:
                    type: string
                  status:
                    type: string
                  idempotent_replay:
                    type: boolean
        '200':
          description: Idempotent replay
          content:
            application/json:
              schema:
                type: object
                properties:
                  activity_id:
                    type: string
                  status:
                    type: string
                  idempotent_replay:
                    type: boolean
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
    get:
      summary: List activities by user
      description: Retrieve the most recent activities for a given user within the
        tenant context.
      security:
      - bearerAuth: []
      tags:
      - Activities
      operationId: listUserActivities
      parameters:
      - name: user_id
        in: query
        required: true
        schema:
          type: string
      - name: cursor
        in: query
        schema:
          type: string
      - name: limit
        in: query
        schema:
          type: integer
          default: 20
      responses:
        '200':
          description: List of activities
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Activity'
                  next_cursor:
                    type: string
  /v1/activities/metrics:
    get:
      summary: Activity metrics
      description: Retrieve aggregate statistics and a recent activity timeline for a specific user.
      security:
      - bearerAuth: []
      tags:
      - Activities
      operationId: getActivityMetrics
      parameters:
      - name: user_id
        in: query
        required: true
        schema:
          type: string
        description: Identifier of the user whose activities should be summarised.
      - name: timeline_limit
        in: query
        schema:
          type: integer
          default: 10
          maximum: 50
        description: Maximum number of recent activities to include in the response timeline.
      - name: window_hours
        in: query
        schema:
          type: integer
          default: 24
          minimum: 0
        description: Optional lookback window (in hours) to apply when computing metrics. Use 0 to include all history.
      responses:
        '200':
          description: Metrics and timeline data for the requested user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityMetricsResponse'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
  /v1/activities/{id}:
    get:
      summary: Get activity by ID
      description: Fetch a single activity by identifier if the caller has tenant
        access.
      security:
      - bearerAuth: []
      tags:
      - Activities
      operationId: getActivityById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Activity found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
        '404':
          description: Activity not found
