name: Build Distributions

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  go-binaries:
    name: Go Services
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: activity-service
            path: services/activity-service
            binary: activity-service
          - name: exercise-ontology-service
            path: services/exercise-ontology-service
            binary: exercise-ontology-service
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      - name: Build binary
        working-directory: ${{ matrix.path }}
        env:
          CGO_ENABLED: '0'
        run: |
          go mod download
          mkdir -p dist
          go build -trimpath -ldflags "-s -w" -o dist/${{ matrix.binary }} ./cmd/api
      - name: Package artifact
        working-directory: ${{ matrix.path }}/dist
        run: |
          tar -czf ${{ matrix.binary }}-${{ github.ref_name }}.tar.gz ${{ matrix.binary }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-${{ matrix.name }}-${{ github.ref_name }}
          path: ${{ matrix.path }}/dist/${{ matrix.binary }}-${{ github.ref_name }}.tar.gz

  python-package:
    name: Identity Service Package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build wheel and sdist
        working-directory: services/identity-service
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir build
          python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: identity-service-${{ github.ref_name }}
          path: |
            services/identity-service/dist/*.whl
            services/identity-service/dist/*.tar.gz

  frontend-dist:
    name: Frontend Bundle
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
          run_install: false
      - name: Install dependencies
        working-directory: frontend/web
        run: pnpm install --frozen-lockfile
      - name: Build production bundle
        working-directory: frontend/web
        run: pnpm build
      - name: Package artifact
        working-directory: frontend/web
        run: |
          tar -czf web-dist-${{ github.ref_name }}.tar.gz dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist-${{ github.ref_name }}
          path: frontend/web/web-dist-${{ github.ref_name }}.tar.gz

  publish-release:
    name: Publish Release
    needs:
      - go-binaries
      - python-package
      - frontend-dist
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
      - name: List assets
        run: |
          echo "Release assets to publish:"
          find release-assets -maxdepth 5 -type f -print
      - name: Publish GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          mapfile -d '' -t assets < <(find release-assets -type f -print0)
          if [ "${#assets[@]}" -eq 0 ]; then
            echo "No artifacts found to publish."
            exit 1
          fi
          if gh release view "$TAG_NAME" >/dev/null 2>&1; then
            echo "Release $TAG_NAME already exists. Uploading assets with clobber."
            gh release upload "$TAG_NAME" "${assets[@]}" --clobber
          else
            echo "Creating release $TAG_NAME with generated notes."
            gh release create "$TAG_NAME" "${assets[@]}" --generate-notes
          fi
