name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pre-pull images
        run: task prepull:images

      - name: Go build/tests
        run: |
          task build:go
          task test:go

      - name: Python lint/tests
        run: |
          task lint:python
          task test:python

      - name: API docs lint
        run: task docs:lint

      - name: Frontend install
        run: task web:install

      - name: Frontend build
        run: task web:build

      - name: Frontend tests
        run: task web:test

      - name: Integration tests
        run: task test:integration

      - name: Smoke test docker-compose stack
        run: task smoke:compose

      - name: Upload compose logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: infrastructure/compose/*.log
        continue-on-error: true
